feat: Page on writing insights
2pisoftware/cmfive-docs pull request #11
Opened 2021-08-18 03:29 UTC by Tinystep1

Added page on code needed when writing insights in order for it to work correctly.

refs: 10167

2021-08-19 22:19 UTC, strongishllama requested changes
Hey, @Tinystep1 nice work. Just two small typos to fix. I've been using this VS Code [extension](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) to catch my typos, thought you might find it helpful!

2021-08-19 22:19 UTC, strongishllama commented on _documentation/core-modules/insight/insight.md
> +These variables will indicate to users which isnight is which.
@Tinystep1 Small typo on ```insight``` here.

2021-08-19 22:19 UTC, strongishllama commented on _documentation/core-modules/insight/insight.md
> +getFilters will be an array, which sets up the parameters the user can choose. Before viewing an insight, the user may specify it to only show information from specififc dates, for certain users, etc
@Tinystep1 Small typo on ```specific``` here.

2021-08-20 04:43 UTC, strongishllama approved these changes

2021-08-24 21:47 UTC, merged

2021-08-25 08:41 UTC, Tinystep1 commented
Thanks. I had been copying it from my localhost and running it through
Grammarly, so I'm surprised I didn't pick up on these. I'll try the
extension too

On Fri, Aug 20, 2021 at 2:43 PM Taliesin Millhouse ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/2pisoftware/cmfive-docs/pull/11#pullrequestreview-734662098>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANK3JWRX2IEHJIZHOZ4AYKDT5XMQZANCNFSM5CLEHG3A>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>